### PR TITLE
feature/i18n-ja

### PR DESCRIPTION
**Pull request by satomikenta-org**
### Feature i18n-ja

Changes I made in this pull request:
- add i18n for Japanese.

### CODE REVIEW

**Comment by cpylua** [comment]
Hi,

Please run `yarn prettify` to fix lint errors.

**Comment by satomikenta-org** [comment]
I did.
 thanks !

**Review by cpylua — CHANGES_REQUESTED** [review]
Here's how to see your translations in action:

1. Change [`site/src/App.tsx#85`](https://github.com/youzan/zent/blob/ec4c36069e3a8a374d1b04ad1f5b1c562677bb73/site/src/App.tsx#L85) to
  ```
<I18nProvider value={jaJPLocale}>
     <Switch>{routeData['en-US'].map(renderRouter)}</Switch>
</I18nProvider>
  ```
2. Make sure you have `coreutils` installed(run `brew install coreutils` on OSX). Then run

```
yarn bootstrap
yarn dev
```

A dev version of the documentation pages will open if all goes well. The docs and demos will be in English but components are rendered with `jaJP` locale. You can check your translations by navigating to each component.

**Be sure NOT to commit `site/src/App.tsx` changes.**

**Comment by satomikenta-org** [comment]
I modified ja to ja-JP (LanguageCode-CountryCode).
Also, checked translated Japanese text in site. thanks.

**Pull request merged**
